///////////////////////////////////////
// PIDCalibBranches.cc               //
// Author: Matthew Kenzie            //
// Auto-generated                    //
///////////////////////////////////////

#include "../interface/PIDCalibBranches.h"

PIDCalibBranches::PIDCalibBranches(){} 																	 
PIDCalibBranches::~PIDCalibBranches(){} 																	 
void PIDCalibBranches::setInputBranches(Looper *l, TTree *tree){ 
	if (l->itype<0) tree->SetBranchAddress("B_s0_BKGCAT", l->B_s0_BKGCAT, &(l->b_B_s0_BKGCAT));
	tree->SetBranchAddress("B_s0_DIRA_OWNPV", l->B_s0_DIRA_OWNPV, &(l->b_B_s0_DIRA_OWNPV));
	tree->SetBranchAddress("B_s0_ENDVERTEX_CHI2", l->B_s0_ENDVERTEX_CHI2, &(l->b_B_s0_ENDVERTEX_CHI2));
	tree->SetBranchAddress("B_s0_ETA", l->B_s0_ETA, &(l->b_B_s0_ETA));
	tree->SetBranchAddress("B_s0_FDCHI2_OWNPV", l->B_s0_FDCHI2_OWNPV, &(l->b_B_s0_FDCHI2_OWNPV));
	tree->SetBranchAddress("B_s0_FD_OWNPV", l->B_s0_FD_OWNPV, &(l->b_B_s0_FD_OWNPV));
	tree->SetBranchAddress("B_s0_Hlt1DiHadronDecision_TOS", l->B_s0_Hlt1DiHadronDecision_TOS, &(l->b_B_s0_Hlt1DiHadronDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt1SingleHadronDecision_TOS", l->B_s0_Hlt1SingleHadronDecision_TOS, &(l->b_B_s0_Hlt1SingleHadronDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt1TrackAllL0Decision_TOS", l->B_s0_Hlt1TrackAllL0Decision_TOS, &(l->b_B_s0_Hlt1TrackAllL0Decision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2B2HHDecision_TOS", l->B_s0_Hlt2B2HHDecision_TOS, &(l->b_B_s0_Hlt2B2HHDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo2BodyBBDTDecision_TOS", l->B_s0_Hlt2Topo2BodyBBDTDecision_TOS, &(l->b_B_s0_Hlt2Topo2BodyBBDTDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo2BodySimpleDecision_TOS", l->B_s0_Hlt2Topo2BodySimpleDecision_TOS, &(l->b_B_s0_Hlt2Topo2BodySimpleDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo3BodyBBDTDecision_TOS", l->B_s0_Hlt2Topo3BodyBBDTDecision_TOS, &(l->b_B_s0_Hlt2Topo3BodyBBDTDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo3BodySimpleDecision_TOS", l->B_s0_Hlt2Topo3BodySimpleDecision_TOS, &(l->b_B_s0_Hlt2Topo3BodySimpleDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo4BodyBBDTDecision_TOS", l->B_s0_Hlt2Topo4BodyBBDTDecision_TOS, &(l->b_B_s0_Hlt2Topo4BodyBBDTDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2Topo4BodySimpleDecision_TOS", l->B_s0_Hlt2Topo4BodySimpleDecision_TOS, &(l->b_B_s0_Hlt2Topo4BodySimpleDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS", l->B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS, &(l->b_B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS));
	tree->SetBranchAddress("B_s0_Hlt2TopoOSTF4BodyDecision_TOS", l->B_s0_Hlt2TopoOSTF4BodyDecision_TOS, &(l->b_B_s0_Hlt2TopoOSTF4BodyDecision_TOS));
	tree->SetBranchAddress("B_s0_IPCHI2_OWNPV", l->B_s0_IPCHI2_OWNPV, &(l->b_B_s0_IPCHI2_OWNPV));
	tree->SetBranchAddress("B_s0_IP_OWNPV", l->B_s0_IP_OWNPV, &(l->b_B_s0_IP_OWNPV));
	tree->SetBranchAddress("B_s0_L0Global_TIS", l->B_s0_L0Global_TIS, &(l->b_B_s0_L0Global_TIS));
	tree->SetBranchAddress("B_s0_L0HadronDecision_TOS", l->B_s0_L0HadronDecision_TOS, &(l->b_B_s0_L0HadronDecision_TOS));
	tree->SetBranchAddress("B_s0_M", l->B_s0_M, &(l->b_B_s0_M));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_GD_GD_MOTHER_ID", l->B_s0_MC_GD_GD_MOTHER_ID, &(l->b_B_s0_MC_GD_GD_MOTHER_ID));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_GD_GD_MOTHER_KEY", l->B_s0_MC_GD_GD_MOTHER_KEY, &(l->b_B_s0_MC_GD_GD_MOTHER_KEY));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_GD_MOTHER_ID", l->B_s0_MC_GD_MOTHER_ID, &(l->b_B_s0_MC_GD_MOTHER_ID));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_GD_MOTHER_KEY", l->B_s0_MC_GD_MOTHER_KEY, &(l->b_B_s0_MC_GD_MOTHER_KEY));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_MOTHER_ID", l->B_s0_MC_MOTHER_ID, &(l->b_B_s0_MC_MOTHER_ID));
	if (l->itype<0) tree->SetBranchAddress("B_s0_MC_MOTHER_KEY", l->B_s0_MC_MOTHER_KEY, &(l->b_B_s0_MC_MOTHER_KEY));
	tree->SetBranchAddress("B_s0_MM", l->B_s0_MM, &(l->b_B_s0_MM));
	tree->SetBranchAddress("B_s0_MMERR", l->B_s0_MMERR, &(l->b_B_s0_MMERR));
	tree->SetBranchAddress("B_s0_OWNPV_CHI2", l->B_s0_OWNPV_CHI2, &(l->b_B_s0_OWNPV_CHI2));
	tree->SetBranchAddress("B_s0_P", l->B_s0_P, &(l->b_B_s0_P));
	tree->SetBranchAddress("B_s0_PE", l->B_s0_PE, &(l->b_B_s0_PE));
	tree->SetBranchAddress("B_s0_PT", l->B_s0_PT, &(l->b_B_s0_PT));
	tree->SetBranchAddress("B_s0_PX", l->B_s0_PX, &(l->b_B_s0_PX));
	tree->SetBranchAddress("B_s0_PY", l->B_s0_PY, &(l->b_B_s0_PY));
	tree->SetBranchAddress("B_s0_PZ", l->B_s0_PZ, &(l->b_B_s0_PZ));
	tree->SetBranchAddress("B_s0_Phi", l->B_s0_Phi, &(l->b_B_s0_Phi));
	tree->SetBranchAddress("B_s0_TAGCAT", l->B_s0_TAGCAT, &(l->b_B_s0_TAGCAT));
	tree->SetBranchAddress("B_s0_TAGCAT_OS", l->B_s0_TAGCAT_OS, &(l->b_B_s0_TAGCAT_OS));
	tree->SetBranchAddress("B_s0_TAGDECISION", l->B_s0_TAGDECISION, &(l->b_B_s0_TAGDECISION));
	tree->SetBranchAddress("B_s0_TAGDECISION_OS", l->B_s0_TAGDECISION_OS, &(l->b_B_s0_TAGDECISION_OS));
	tree->SetBranchAddress("B_s0_TAGGER", l->B_s0_TAGGER, &(l->b_B_s0_TAGGER));
	tree->SetBranchAddress("B_s0_TAGOMEGA", l->B_s0_TAGOMEGA, &(l->b_B_s0_TAGOMEGA));
	tree->SetBranchAddress("B_s0_TAGOMEGA_OS", l->B_s0_TAGOMEGA_OS, &(l->b_B_s0_TAGOMEGA_OS));
	tree->SetBranchAddress("B_s0_TAU", l->B_s0_TAU, &(l->b_B_s0_TAU));
	tree->SetBranchAddress("B_s0_TAUCHI2", l->B_s0_TAUCHI2, &(l->b_B_s0_TAUCHI2));
	tree->SetBranchAddress("B_s0_TAUERR", l->B_s0_TAUERR, &(l->b_B_s0_TAUERR));
	tree->SetBranchAddress("Kminus_ETA", l->Kminus_ETA, &(l->b_Kminus_ETA));
	tree->SetBranchAddress("Kminus_IPCHI2_OWNPV", l->Kminus_IPCHI2_OWNPV, &(l->b_Kminus_IPCHI2_OWNPV));
	tree->SetBranchAddress("Kminus_IP_OWNPV", l->Kminus_IP_OWNPV, &(l->b_Kminus_IP_OWNPV));
	tree->SetBranchAddress("Kminus_M", l->Kminus_M, &(l->b_Kminus_M));
	tree->SetBranchAddress("Kminus_ORIVX_CHI2", l->Kminus_ORIVX_CHI2, &(l->b_Kminus_ORIVX_CHI2));
	tree->SetBranchAddress("Kminus_P", l->Kminus_P, &(l->b_Kminus_P));
	tree->SetBranchAddress("Kminus_PE", l->Kminus_PE, &(l->b_Kminus_PE));
	tree->SetBranchAddress("Kminus_PIDK", l->Kminus_PIDK, &(l->b_Kminus_PIDK));
	tree->SetBranchAddress("Kminus_PIDe", l->Kminus_PIDe, &(l->b_Kminus_PIDe));
	tree->SetBranchAddress("Kminus_PIDmu", l->Kminus_PIDmu, &(l->b_Kminus_PIDmu));
	tree->SetBranchAddress("Kminus_PIDp", l->Kminus_PIDp, &(l->b_Kminus_PIDp));
	tree->SetBranchAddress("Kminus_PT", l->Kminus_PT, &(l->b_Kminus_PT));
	tree->SetBranchAddress("Kminus_PX", l->Kminus_PX, &(l->b_Kminus_PX));
	tree->SetBranchAddress("Kminus_PY", l->Kminus_PY, &(l->b_Kminus_PY));
	tree->SetBranchAddress("Kminus_PZ", l->Kminus_PZ, &(l->b_Kminus_PZ));
	tree->SetBranchAddress("Kminus_ProbNNk", l->Kminus_ProbNNk, &(l->b_Kminus_ProbNNk));
	tree->SetBranchAddress("Kminus_ProbNNp", l->Kminus_ProbNNp, &(l->b_Kminus_ProbNNp));
	tree->SetBranchAddress("Kminus_ProbNNpi", l->Kminus_ProbNNpi, &(l->b_Kminus_ProbNNpi));
	tree->SetBranchAddress("Kminus_TRACK_CHI2NDOF", l->Kminus_TRACK_CHI2NDOF, &(l->b_Kminus_TRACK_CHI2NDOF));
	tree->SetBranchAddress("Kminus_isMuon", l->Kminus_isMuon, &(l->b_Kminus_isMuon));
	tree->SetBranchAddress("Kplus_ETA", l->Kplus_ETA, &(l->b_Kplus_ETA));
	tree->SetBranchAddress("Kplus_IPCHI2_OWNPV", l->Kplus_IPCHI2_OWNPV, &(l->b_Kplus_IPCHI2_OWNPV));
	tree->SetBranchAddress("Kplus_IP_OWNPV", l->Kplus_IP_OWNPV, &(l->b_Kplus_IP_OWNPV));
	tree->SetBranchAddress("Kplus_M", l->Kplus_M, &(l->b_Kplus_M));
	tree->SetBranchAddress("Kplus_ORIVX_CHI2", l->Kplus_ORIVX_CHI2, &(l->b_Kplus_ORIVX_CHI2));
	tree->SetBranchAddress("Kplus_P", l->Kplus_P, &(l->b_Kplus_P));
	tree->SetBranchAddress("Kplus_PE", l->Kplus_PE, &(l->b_Kplus_PE));
	tree->SetBranchAddress("Kplus_PIDK", l->Kplus_PIDK, &(l->b_Kplus_PIDK));
	tree->SetBranchAddress("Kplus_PIDe", l->Kplus_PIDe, &(l->b_Kplus_PIDe));
	tree->SetBranchAddress("Kplus_PIDmu", l->Kplus_PIDmu, &(l->b_Kplus_PIDmu));
	tree->SetBranchAddress("Kplus_PIDp", l->Kplus_PIDp, &(l->b_Kplus_PIDp));
	tree->SetBranchAddress("Kplus_PT", l->Kplus_PT, &(l->b_Kplus_PT));
	tree->SetBranchAddress("Kplus_PX", l->Kplus_PX, &(l->b_Kplus_PX));
	tree->SetBranchAddress("Kplus_PY", l->Kplus_PY, &(l->b_Kplus_PY));
	tree->SetBranchAddress("Kplus_PZ", l->Kplus_PZ, &(l->b_Kplus_PZ));
	tree->SetBranchAddress("Kplus_ProbNNk", l->Kplus_ProbNNk, &(l->b_Kplus_ProbNNk));
	tree->SetBranchAddress("Kplus_ProbNNp", l->Kplus_ProbNNp, &(l->b_Kplus_ProbNNp));
	tree->SetBranchAddress("Kplus_ProbNNpi", l->Kplus_ProbNNpi, &(l->b_Kplus_ProbNNpi));
	tree->SetBranchAddress("Kplus_TRACK_CHI2NDOF", l->Kplus_TRACK_CHI2NDOF, &(l->b_Kplus_TRACK_CHI2NDOF));
	tree->SetBranchAddress("Kplus_isMuon", l->Kplus_isMuon, &(l->b_Kplus_isMuon));
	tree->SetBranchAddress("Kst_CosTheta", l->Kst_CosTheta, &(l->b_Kst_CosTheta));
	tree->SetBranchAddress("Kst_DIRA_ORIVX", l->Kst_DIRA_ORIVX, &(l->b_Kst_DIRA_ORIVX));
	tree->SetBranchAddress("Kst_DIRA_OWNPV", l->Kst_DIRA_OWNPV, &(l->b_Kst_DIRA_OWNPV));
	tree->SetBranchAddress("Kst_ENDVERTEX_CHI2", l->Kst_ENDVERTEX_CHI2, &(l->b_Kst_ENDVERTEX_CHI2));
	tree->SetBranchAddress("Kst_ETA", l->Kst_ETA, &(l->b_Kst_ETA));
	tree->SetBranchAddress("Kst_FDCHI2_ORIVX", l->Kst_FDCHI2_ORIVX, &(l->b_Kst_FDCHI2_ORIVX));
	tree->SetBranchAddress("Kst_FDCHI2_OWNPV", l->Kst_FDCHI2_OWNPV, &(l->b_Kst_FDCHI2_OWNPV));
	tree->SetBranchAddress("Kst_FD_ORIVX", l->Kst_FD_ORIVX, &(l->b_Kst_FD_ORIVX));
	tree->SetBranchAddress("Kst_FD_OWNPV", l->Kst_FD_OWNPV, &(l->b_Kst_FD_OWNPV));
	tree->SetBranchAddress("Kst_IPCHI2_OWNPV", l->Kst_IPCHI2_OWNPV, &(l->b_Kst_IPCHI2_OWNPV));
	tree->SetBranchAddress("Kst_IP_OWNPV", l->Kst_IP_OWNPV, &(l->b_Kst_IP_OWNPV));
	tree->SetBranchAddress("Kst_M", l->Kst_M, &(l->b_Kst_M));
	tree->SetBranchAddress("Kst_MM", l->Kst_MM, &(l->b_Kst_MM));
	tree->SetBranchAddress("Kst_MMERR", l->Kst_MMERR, &(l->b_Kst_MMERR));
	tree->SetBranchAddress("Kst_P", l->Kst_P, &(l->b_Kst_P));
	tree->SetBranchAddress("Kst_PE", l->Kst_PE, &(l->b_Kst_PE));
	tree->SetBranchAddress("Kst_PT", l->Kst_PT, &(l->b_Kst_PT));
	tree->SetBranchAddress("Kst_PX", l->Kst_PX, &(l->b_Kst_PX));
	tree->SetBranchAddress("Kst_PY", l->Kst_PY, &(l->b_Kst_PY));
	tree->SetBranchAddress("Kst_PZ", l->Kst_PZ, &(l->b_Kst_PZ));
	tree->SetBranchAddress("Kstb_CosTheta", l->Kstb_CosTheta, &(l->b_Kstb_CosTheta));
	tree->SetBranchAddress("Kstb_DIRA_ORIVX", l->Kstb_DIRA_ORIVX, &(l->b_Kstb_DIRA_ORIVX));
	tree->SetBranchAddress("Kstb_DIRA_OWNPV", l->Kstb_DIRA_OWNPV, &(l->b_Kstb_DIRA_OWNPV));
	tree->SetBranchAddress("Kstb_ENDVERTEX_CHI2", l->Kstb_ENDVERTEX_CHI2, &(l->b_Kstb_ENDVERTEX_CHI2));
	tree->SetBranchAddress("Kstb_ETA", l->Kstb_ETA, &(l->b_Kstb_ETA));
	tree->SetBranchAddress("Kstb_FDCHI2_ORIVX", l->Kstb_FDCHI2_ORIVX, &(l->b_Kstb_FDCHI2_ORIVX));
	tree->SetBranchAddress("Kstb_FDCHI2_OWNPV", l->Kstb_FDCHI2_OWNPV, &(l->b_Kstb_FDCHI2_OWNPV));
	tree->SetBranchAddress("Kstb_FD_ORIVX", l->Kstb_FD_ORIVX, &(l->b_Kstb_FD_ORIVX));
	tree->SetBranchAddress("Kstb_FD_OWNPV", l->Kstb_FD_OWNPV, &(l->b_Kstb_FD_OWNPV));
	tree->SetBranchAddress("Kstb_IPCHI2_OWNPV", l->Kstb_IPCHI2_OWNPV, &(l->b_Kstb_IPCHI2_OWNPV));
	tree->SetBranchAddress("Kstb_IP_OWNPV", l->Kstb_IP_OWNPV, &(l->b_Kstb_IP_OWNPV));
	tree->SetBranchAddress("Kstb_M", l->Kstb_M, &(l->b_Kstb_M));
	tree->SetBranchAddress("Kstb_MM", l->Kstb_MM, &(l->b_Kstb_MM));
	tree->SetBranchAddress("Kstb_MMERR", l->Kstb_MMERR, &(l->b_Kstb_MMERR));
	tree->SetBranchAddress("Kstb_P", l->Kstb_P, &(l->b_Kstb_P));
	tree->SetBranchAddress("Kstb_PE", l->Kstb_PE, &(l->b_Kstb_PE));
	tree->SetBranchAddress("Kstb_PT", l->Kstb_PT, &(l->b_Kstb_PT));
	tree->SetBranchAddress("Kstb_PX", l->Kstb_PX, &(l->b_Kstb_PX));
	tree->SetBranchAddress("Kstb_PY", l->Kstb_PY, &(l->b_Kstb_PY));
	tree->SetBranchAddress("Kstb_PZ", l->Kstb_PZ, &(l->b_Kstb_PZ));
	tree->SetBranchAddress("M_KKPiMinus", l->M_KKPiMinus, &(l->b_M_KKPiMinus));
	tree->SetBranchAddress("M_KKPiPlus", l->M_KKPiPlus, &(l->b_M_KKPiPlus));
	tree->SetBranchAddress("PVCHI2", l->PVCHI2, &(l->b_PVCHI2));
	tree->SetBranchAddress("PVNDOF", l->PVNDOF, &(l->b_PVNDOF));
	tree->SetBranchAddress("PVNTRACKS", l->PVNTRACKS, &(l->b_PVNTRACKS));
	tree->SetBranchAddress("PVX", l->PVX, &(l->b_PVX));
	tree->SetBranchAddress("PVXERR", l->PVXERR, &(l->b_PVXERR));
	tree->SetBranchAddress("PVY", l->PVY, &(l->b_PVY));
	tree->SetBranchAddress("PVYERR", l->PVYERR, &(l->b_PVYERR));
	tree->SetBranchAddress("PVZ", l->PVZ, &(l->b_PVZ));
	tree->SetBranchAddress("PVZERR", l->PVZERR, &(l->b_PVZERR));
	tree->SetBranchAddress("Piminus_ETA", l->Piminus_ETA, &(l->b_Piminus_ETA));
	tree->SetBranchAddress("Piminus_IPCHI2_OWNPV", l->Piminus_IPCHI2_OWNPV, &(l->b_Piminus_IPCHI2_OWNPV));
	tree->SetBranchAddress("Piminus_IP_OWNPV", l->Piminus_IP_OWNPV, &(l->b_Piminus_IP_OWNPV));
	tree->SetBranchAddress("Piminus_M", l->Piminus_M, &(l->b_Piminus_M));
	tree->SetBranchAddress("Piminus_ORIVX_CHI2", l->Piminus_ORIVX_CHI2, &(l->b_Piminus_ORIVX_CHI2));
	tree->SetBranchAddress("Piminus_P", l->Piminus_P, &(l->b_Piminus_P));
	tree->SetBranchAddress("Piminus_PE", l->Piminus_PE, &(l->b_Piminus_PE));
	tree->SetBranchAddress("Piminus_PIDK", l->Piminus_PIDK, &(l->b_Piminus_PIDK));
	tree->SetBranchAddress("Piminus_PIDe", l->Piminus_PIDe, &(l->b_Piminus_PIDe));
	tree->SetBranchAddress("Piminus_PIDmu", l->Piminus_PIDmu, &(l->b_Piminus_PIDmu));
	tree->SetBranchAddress("Piminus_PIDp", l->Piminus_PIDp, &(l->b_Piminus_PIDp));
	tree->SetBranchAddress("Piminus_PT", l->Piminus_PT, &(l->b_Piminus_PT));
	tree->SetBranchAddress("Piminus_PX", l->Piminus_PX, &(l->b_Piminus_PX));
	tree->SetBranchAddress("Piminus_PY", l->Piminus_PY, &(l->b_Piminus_PY));
	tree->SetBranchAddress("Piminus_PZ", l->Piminus_PZ, &(l->b_Piminus_PZ));
	tree->SetBranchAddress("Piminus_ProbNNk", l->Piminus_ProbNNk, &(l->b_Piminus_ProbNNk));
	tree->SetBranchAddress("Piminus_ProbNNp", l->Piminus_ProbNNp, &(l->b_Piminus_ProbNNp));
	tree->SetBranchAddress("Piminus_ProbNNpi", l->Piminus_ProbNNpi, &(l->b_Piminus_ProbNNpi));
	tree->SetBranchAddress("Piminus_TRACK_CHI2NDOF", l->Piminus_TRACK_CHI2NDOF, &(l->b_Piminus_TRACK_CHI2NDOF));
	tree->SetBranchAddress("Piminus_isMuon", l->Piminus_isMuon, &(l->b_Piminus_isMuon));
	tree->SetBranchAddress("Piplus_ETA", l->Piplus_ETA, &(l->b_Piplus_ETA));
	tree->SetBranchAddress("Piplus_IPCHI2_OWNPV", l->Piplus_IPCHI2_OWNPV, &(l->b_Piplus_IPCHI2_OWNPV));
	tree->SetBranchAddress("Piplus_IP_OWNPV", l->Piplus_IP_OWNPV, &(l->b_Piplus_IP_OWNPV));
	tree->SetBranchAddress("Piplus_M", l->Piplus_M, &(l->b_Piplus_M));
	tree->SetBranchAddress("Piplus_ORIVX_CHI2", l->Piplus_ORIVX_CHI2, &(l->b_Piplus_ORIVX_CHI2));
	tree->SetBranchAddress("Piplus_P", l->Piplus_P, &(l->b_Piplus_P));
	tree->SetBranchAddress("Piplus_PE", l->Piplus_PE, &(l->b_Piplus_PE));
	tree->SetBranchAddress("Piplus_PIDK", l->Piplus_PIDK, &(l->b_Piplus_PIDK));
	tree->SetBranchAddress("Piplus_PIDe", l->Piplus_PIDe, &(l->b_Piplus_PIDe));
	tree->SetBranchAddress("Piplus_PIDmu", l->Piplus_PIDmu, &(l->b_Piplus_PIDmu));
	tree->SetBranchAddress("Piplus_PIDp", l->Piplus_PIDp, &(l->b_Piplus_PIDp));
	tree->SetBranchAddress("Piplus_PT", l->Piplus_PT, &(l->b_Piplus_PT));
	tree->SetBranchAddress("Piplus_PX", l->Piplus_PX, &(l->b_Piplus_PX));
	tree->SetBranchAddress("Piplus_PY", l->Piplus_PY, &(l->b_Piplus_PY));
	tree->SetBranchAddress("Piplus_PZ", l->Piplus_PZ, &(l->b_Piplus_PZ));
	tree->SetBranchAddress("Piplus_ProbNNk", l->Piplus_ProbNNk, &(l->b_Piplus_ProbNNk));
	tree->SetBranchAddress("Piplus_ProbNNp", l->Piplus_ProbNNp, &(l->b_Piplus_ProbNNp));
	tree->SetBranchAddress("Piplus_ProbNNpi", l->Piplus_ProbNNpi, &(l->b_Piplus_ProbNNpi));
	tree->SetBranchAddress("Piplus_TRACK_CHI2NDOF", l->Piplus_TRACK_CHI2NDOF, &(l->b_Piplus_TRACK_CHI2NDOF));
	tree->SetBranchAddress("Piplus_isMuon", l->Piplus_isMuon, &(l->b_Piplus_isMuon));
	tree->SetBranchAddress("Polarity", l->Polarity, &(l->b_Polarity));
	tree->SetBranchAddress("cut_based_pid", l->cut_based_pid, &(l->b_cut_based_pid));
	tree->SetBranchAddress("eventNumber", l->eventNumber, &(l->b_eventNumber));
	tree->SetBranchAddress("max_track_chi2", l->max_track_chi2, &(l->b_max_track_chi2));
	tree->SetBranchAddress("nBackTracks", l->nBackTracks, &(l->b_nBackTracks));
	tree->SetBranchAddress("nCandidate", l->nCandidate, &(l->b_nCandidate));
	tree->SetBranchAddress("nDownstreamTracks", l->nDownstreamTracks, &(l->b_nDownstreamTracks));
	tree->SetBranchAddress("nITClusters", l->nITClusters, &(l->b_nITClusters));
	tree->SetBranchAddress("nLongTracks", l->nLongTracks, &(l->b_nLongTracks));
	tree->SetBranchAddress("nMuonCoordsS0", l->nMuonCoordsS0, &(l->b_nMuonCoordsS0));
	tree->SetBranchAddress("nMuonCoordsS1", l->nMuonCoordsS1, &(l->b_nMuonCoordsS1));
	tree->SetBranchAddress("nMuonCoordsS2", l->nMuonCoordsS2, &(l->b_nMuonCoordsS2));
	tree->SetBranchAddress("nMuonCoordsS3", l->nMuonCoordsS3, &(l->b_nMuonCoordsS3));
	tree->SetBranchAddress("nMuonCoordsS4", l->nMuonCoordsS4, &(l->b_nMuonCoordsS4));
	tree->SetBranchAddress("nMuonTracks", l->nMuonTracks, &(l->b_nMuonTracks));
	tree->SetBranchAddress("nOTClusters", l->nOTClusters, &(l->b_nOTClusters));
	tree->SetBranchAddress("nPV", l->nPV, &(l->b_nPV));
	tree->SetBranchAddress("nPVs", l->nPVs, &(l->b_nPVs));
	tree->SetBranchAddress("nRich1Hits", l->nRich1Hits, &(l->b_nRich1Hits));
	tree->SetBranchAddress("nRich2Hits", l->nRich2Hits, &(l->b_nRich2Hits));
	tree->SetBranchAddress("nSPDHits", l->nSPDHits, &(l->b_nSPDHits));
	tree->SetBranchAddress("nTTClusters", l->nTTClusters, &(l->b_nTTClusters));
	tree->SetBranchAddress("nTTracks", l->nTTracks, &(l->b_nTTracks));
	tree->SetBranchAddress("nTracks", l->nTracks, &(l->b_nTracks));
	tree->SetBranchAddress("nUpstreamTracks", l->nUpstreamTracks, &(l->b_nUpstreamTracks));
	tree->SetBranchAddress("nVeloClusters", l->nVeloClusters, &(l->b_nVeloClusters));
	tree->SetBranchAddress("nVeloTracks", l->nVeloTracks, &(l->b_nVeloTracks));
	tree->SetBranchAddress("runNumber", l->runNumber, &(l->b_runNumber));
	tree->SetBranchAddress("totCandidates", l->totCandidates, &(l->b_totCandidates));

}

void PIDCalibBranches::initialiseVariables(Looper *l) {
	l->B_s0_BKGCAT                           = new Int_t(0);
	l->B_s0_DIRA_OWNPV                       = new Double_t(0);
	l->B_s0_ENDVERTEX_CHI2                   = new Double_t(0);
	l->B_s0_ETA                              = new Double_t(0);
	l->B_s0_FDCHI2_OWNPV                     = new Double_t(0);
	l->B_s0_FD_OWNPV                         = new Double_t(0);
	l->B_s0_Hlt1DiHadronDecision_TOS         = new Bool_t(0);
	l->B_s0_Hlt1SingleHadronDecision_TOS     = new Bool_t(0);
	l->B_s0_Hlt1TrackAllL0Decision_TOS       = new Bool_t(0);
	l->B_s0_Hlt2B2HHDecision_TOS             = new Bool_t(0);
	l->B_s0_Hlt2Topo2BodyBBDTDecision_TOS    = new Bool_t(0);
	l->B_s0_Hlt2Topo2BodySimpleDecision_TOS  = new Bool_t(0);
	l->B_s0_Hlt2Topo3BodyBBDTDecision_TOS    = new Bool_t(0);
	l->B_s0_Hlt2Topo3BodySimpleDecision_TOS  = new Bool_t(0);
	l->B_s0_Hlt2Topo4BodyBBDTDecision_TOS    = new Bool_t(0);
	l->B_s0_Hlt2Topo4BodySimpleDecision_TOS  = new Bool_t(0);
	l->B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS  = new Bool_t(0);
	l->B_s0_Hlt2TopoOSTF4BodyDecision_TOS    = new Bool_t(0);
	l->B_s0_IPCHI2_OWNPV                     = new Double_t(0);
	l->B_s0_IP_OWNPV                         = new Double_t(0);
	l->B_s0_L0Global_TIS                     = new Bool_t(0);
	l->B_s0_L0HadronDecision_TOS             = new Bool_t(0);
	l->B_s0_M                                = new Double_t(0);
	l->B_s0_MC_GD_GD_MOTHER_ID               = new Int_t(0);
	l->B_s0_MC_GD_GD_MOTHER_KEY              = new Int_t(0);
	l->B_s0_MC_GD_MOTHER_ID                  = new Int_t(0);
	l->B_s0_MC_GD_MOTHER_KEY                 = new Int_t(0);
	l->B_s0_MC_MOTHER_ID                     = new Int_t(0);
	l->B_s0_MC_MOTHER_KEY                    = new Int_t(0);
	l->B_s0_MM                               = new Double_t(0);
	l->B_s0_MMERR                            = new Double_t(0);
	l->B_s0_OWNPV_CHI2                       = new Double_t(0);
	l->B_s0_P                                = new Double_t(0);
	l->B_s0_PE                               = new Double_t(0);
	l->B_s0_PT                               = new Double_t(0);
	l->B_s0_PX                               = new Double_t(0);
	l->B_s0_PY                               = new Double_t(0);
	l->B_s0_PZ                               = new Double_t(0);
	l->B_s0_Phi                              = new Double_t(0);
	l->B_s0_TAGCAT                           = new Int_t(0);
	l->B_s0_TAGCAT_OS                        = new Int_t(0);
	l->B_s0_TAGDECISION                      = new Int_t(0);
	l->B_s0_TAGDECISION_OS                   = new Int_t(0);
	l->B_s0_TAGGER                           = new Int_t(0);
	l->B_s0_TAGOMEGA                         = new Double_t(0);
	l->B_s0_TAGOMEGA_OS                      = new Double_t(0);
	l->B_s0_TAU                              = new Double_t(0);
	l->B_s0_TAUCHI2                          = new Double_t(0);
	l->B_s0_TAUERR                           = new Double_t(0);
	l->Kminus_ETA                            = new Double_t(0);
	l->Kminus_IPCHI2_OWNPV                   = new Double_t(0);
	l->Kminus_IP_OWNPV                       = new Double_t(0);
	l->Kminus_M                              = new Double_t(0);
	l->Kminus_ORIVX_CHI2                     = new Double_t(0);
	l->Kminus_P                              = new Double_t(0);
	l->Kminus_PE                             = new Double_t(0);
	l->Kminus_PIDK                           = new Double_t(0);
	l->Kminus_PIDe                           = new Double_t(0);
	l->Kminus_PIDmu                          = new Double_t(0);
	l->Kminus_PIDp                           = new Double_t(0);
	l->Kminus_PT                             = new Double_t(0);
	l->Kminus_PX                             = new Double_t(0);
	l->Kminus_PY                             = new Double_t(0);
	l->Kminus_PZ                             = new Double_t(0);
	l->Kminus_ProbNNk                        = new Double_t(0);
	l->Kminus_ProbNNkcorr                    = new Double_t(0);
	l->Kminus_ProbNNp                        = new Double_t(0);
	l->Kminus_ProbNNpi                       = new Double_t(0);
	l->Kminus_ProbNNpicorr                   = new Double_t(0);
	l->Kminus_TRACK_CHI2NDOF                 = new Double_t(0);
	l->Kminus_isMuon                         = new Bool_t(0);
	l->Kplus_ETA                             = new Double_t(0);
	l->Kplus_IPCHI2_OWNPV                    = new Double_t(0);
	l->Kplus_IP_OWNPV                        = new Double_t(0);
	l->Kplus_M                               = new Double_t(0);
	l->Kplus_ORIVX_CHI2                      = new Double_t(0);
	l->Kplus_P                               = new Double_t(0);
	l->Kplus_PE                              = new Double_t(0);
	l->Kplus_PIDK                            = new Double_t(0);
	l->Kplus_PIDe                            = new Double_t(0);
	l->Kplus_PIDmu                           = new Double_t(0);
	l->Kplus_PIDp                            = new Double_t(0);
	l->Kplus_PT                              = new Double_t(0);
	l->Kplus_PX                              = new Double_t(0);
	l->Kplus_PY                              = new Double_t(0);
	l->Kplus_PZ                              = new Double_t(0);
	l->Kplus_ProbNNk                         = new Double_t(0);
	l->Kplus_ProbNNkcorr                     = new Double_t(0);
	l->Kplus_ProbNNp                         = new Double_t(0);
	l->Kplus_ProbNNpi                        = new Double_t(0);
	l->Kplus_ProbNNpicorr                    = new Double_t(0);
	l->Kplus_TRACK_CHI2NDOF                  = new Double_t(0);
	l->Kplus_isMuon                          = new Bool_t(0);
	l->Kst_CosTheta                          = new Double_t(0);
	l->Kst_DIRA_ORIVX                        = new Double_t(0);
	l->Kst_DIRA_OWNPV                        = new Double_t(0);
	l->Kst_ENDVERTEX_CHI2                    = new Double_t(0);
	l->Kst_ETA                               = new Double_t(0);
	l->Kst_FDCHI2_ORIVX                      = new Double_t(0);
	l->Kst_FDCHI2_OWNPV                      = new Double_t(0);
	l->Kst_FD_ORIVX                          = new Double_t(0);
	l->Kst_FD_OWNPV                          = new Double_t(0);
	l->Kst_IPCHI2_OWNPV                      = new Double_t(0);
	l->Kst_IP_OWNPV                          = new Double_t(0);
	l->Kst_M                                 = new Double_t(0);
	l->Kst_MM                                = new Double_t(0);
	l->Kst_MMERR                             = new Double_t(0);
	l->Kst_P                                 = new Double_t(0);
	l->Kst_PE                                = new Double_t(0);
	l->Kst_PT                                = new Double_t(0);
	l->Kst_PX                                = new Double_t(0);
	l->Kst_PY                                = new Double_t(0);
	l->Kst_PZ                                = new Double_t(0);
	l->Kstb_CosTheta                         = new Double_t(0);
	l->Kstb_DIRA_ORIVX                       = new Double_t(0);
	l->Kstb_DIRA_OWNPV                       = new Double_t(0);
	l->Kstb_ENDVERTEX_CHI2                   = new Double_t(0);
	l->Kstb_ETA                              = new Double_t(0);
	l->Kstb_FDCHI2_ORIVX                     = new Double_t(0);
	l->Kstb_FDCHI2_OWNPV                     = new Double_t(0);
	l->Kstb_FD_ORIVX                         = new Double_t(0);
	l->Kstb_FD_OWNPV                         = new Double_t(0);
	l->Kstb_IPCHI2_OWNPV                     = new Double_t(0);
	l->Kstb_IP_OWNPV                         = new Double_t(0);
	l->Kstb_M                                = new Double_t(0);
	l->Kstb_MM                               = new Double_t(0);
	l->Kstb_MMERR                            = new Double_t(0);
	l->Kstb_P                                = new Double_t(0);
	l->Kstb_PE                               = new Double_t(0);
	l->Kstb_PT                               = new Double_t(0);
	l->Kstb_PX                               = new Double_t(0);
	l->Kstb_PY                               = new Double_t(0);
	l->Kstb_PZ                               = new Double_t(0);
	l->M_KKPiMinus                           = new Double_t(0);
	l->M_KKPiPlus                            = new Double_t(0);
	l->PVCHI2                                = new Float_t(0);
	l->PVNDOF                                = new Float_t(0);
	l->PVNTRACKS                             = new Float_t(0);
	l->PVX                                   = new Float_t(0);
	l->PVXERR                                = new Float_t(0);
	l->PVY                                   = new Float_t(0);
	l->PVYERR                                = new Float_t(0);
	l->PVZ                                   = new Float_t(0);
	l->PVZERR                                = new Float_t(0);
	l->Piminus_ETA                           = new Double_t(0);
	l->Piminus_IPCHI2_OWNPV                  = new Double_t(0);
	l->Piminus_IP_OWNPV                      = new Double_t(0);
	l->Piminus_M                             = new Double_t(0);
	l->Piminus_ORIVX_CHI2                    = new Double_t(0);
	l->Piminus_P                             = new Double_t(0);
	l->Piminus_PE                            = new Double_t(0);
	l->Piminus_PIDK                          = new Double_t(0);
	l->Piminus_PIDe                          = new Double_t(0);
	l->Piminus_PIDmu                         = new Double_t(0);
	l->Piminus_PIDp                          = new Double_t(0);
	l->Piminus_PT                            = new Double_t(0);
	l->Piminus_PX                            = new Double_t(0);
	l->Piminus_PY                            = new Double_t(0);
	l->Piminus_PZ                            = new Double_t(0);
	l->Piminus_ProbNNk                       = new Double_t(0);
	l->Piminus_ProbNNkcorr                   = new Double_t(0);
	l->Piminus_ProbNNp                       = new Double_t(0);
	l->Piminus_ProbNNpi                      = new Double_t(0);
	l->Piminus_ProbNNpicorr                  = new Double_t(0);
	l->Piminus_TRACK_CHI2NDOF                = new Double_t(0);
	l->Piminus_isMuon                        = new Bool_t(0);
	l->Piplus_ETA                            = new Double_t(0);
	l->Piplus_IPCHI2_OWNPV                   = new Double_t(0);
	l->Piplus_IP_OWNPV                       = new Double_t(0);
	l->Piplus_M                              = new Double_t(0);
	l->Piplus_ORIVX_CHI2                     = new Double_t(0);
	l->Piplus_P                              = new Double_t(0);
	l->Piplus_PE                             = new Double_t(0);
	l->Piplus_PIDK                           = new Double_t(0);
	l->Piplus_PIDe                           = new Double_t(0);
	l->Piplus_PIDmu                          = new Double_t(0);
	l->Piplus_PIDp                           = new Double_t(0);
	l->Piplus_PT                             = new Double_t(0);
	l->Piplus_PX                             = new Double_t(0);
	l->Piplus_PY                             = new Double_t(0);
	l->Piplus_PZ                             = new Double_t(0);
	l->Piplus_ProbNNk                        = new Double_t(0);
	l->Piplus_ProbNNkcorr                    = new Double_t(0);
	l->Piplus_ProbNNp                        = new Double_t(0);
	l->Piplus_ProbNNpi                       = new Double_t(0);
	l->Piplus_ProbNNpicorr                   = new Double_t(0);
	l->Piplus_TRACK_CHI2NDOF                 = new Double_t(0);
	l->Piplus_isMuon                         = new Bool_t(0);
	l->Polarity                              = new Short_t(0);
	l->cut_based_pid                         = new Bool_t(0);
	l->eventNumber                           = new ULong64_t(0);
	l->max_track_chi2                        = new Double_t(0);
	l->nBackTracks                           = new Int_t(0);
	l->nCandidate                            = new UInt_t(0);
	l->nDownstreamTracks                     = new Int_t(0);
	l->nITClusters                           = new Int_t(0);
	l->nLongTracks                           = new Int_t(0);
	l->nMuonCoordsS0                         = new Int_t(0);
	l->nMuonCoordsS1                         = new Int_t(0);
	l->nMuonCoordsS2                         = new Int_t(0);
	l->nMuonCoordsS3                         = new Int_t(0);
	l->nMuonCoordsS4                         = new Int_t(0);
	l->nMuonTracks                           = new Int_t(0);
	l->nOTClusters                           = new Int_t(0);
	l->nPV                                   = new Int_t(0);
	l->nPVs                                  = new Int_t(0);
	l->nRich1Hits                            = new Int_t(0);
	l->nRich2Hits                            = new Int_t(0);
	l->nSPDHits                              = new Int_t(0);
	l->nTTClusters                           = new Int_t(0);
	l->nTTracks                              = new Int_t(0);
	l->nTracks                               = new Int_t(0);
	l->nUpstreamTracks                       = new Int_t(0);
	l->nVeloClusters                         = new Int_t(0);
	l->nVeloTracks                           = new Int_t(0);
	l->runNumber                             = new UInt_t(0);
	l->totCandidates                         = new ULong64_t(0);

}

void PIDCalibBranches::cleanVariables(Looper *l) {
	delete l->B_s0_BKGCAT;
	delete l->B_s0_DIRA_OWNPV;
	delete l->B_s0_ENDVERTEX_CHI2;
	delete l->B_s0_ETA;
	delete l->B_s0_FDCHI2_OWNPV;
	delete l->B_s0_FD_OWNPV;
	delete l->B_s0_Hlt1DiHadronDecision_TOS;
	delete l->B_s0_Hlt1SingleHadronDecision_TOS;
	delete l->B_s0_Hlt1TrackAllL0Decision_TOS;
	delete l->B_s0_Hlt2B2HHDecision_TOS;
	delete l->B_s0_Hlt2Topo2BodyBBDTDecision_TOS;
	delete l->B_s0_Hlt2Topo2BodySimpleDecision_TOS;
	delete l->B_s0_Hlt2Topo3BodyBBDTDecision_TOS;
	delete l->B_s0_Hlt2Topo3BodySimpleDecision_TOS;
	delete l->B_s0_Hlt2Topo4BodyBBDTDecision_TOS;
	delete l->B_s0_Hlt2Topo4BodySimpleDecision_TOS;
	delete l->B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS;
	delete l->B_s0_Hlt2TopoOSTF4BodyDecision_TOS;
	delete l->B_s0_IPCHI2_OWNPV;
	delete l->B_s0_IP_OWNPV;
	delete l->B_s0_L0Global_TIS;
	delete l->B_s0_L0HadronDecision_TOS;
	delete l->B_s0_M;
	delete l->B_s0_MC_GD_GD_MOTHER_ID;
	delete l->B_s0_MC_GD_GD_MOTHER_KEY;
	delete l->B_s0_MC_GD_MOTHER_ID;
	delete l->B_s0_MC_GD_MOTHER_KEY;
	delete l->B_s0_MC_MOTHER_ID;
	delete l->B_s0_MC_MOTHER_KEY;
	delete l->B_s0_MM;
	delete l->B_s0_MMERR;
	delete l->B_s0_OWNPV_CHI2;
	delete l->B_s0_P;
	delete l->B_s0_PE;
	delete l->B_s0_PT;
	delete l->B_s0_PX;
	delete l->B_s0_PY;
	delete l->B_s0_PZ;
	delete l->B_s0_Phi;
	delete l->B_s0_TAGCAT;
	delete l->B_s0_TAGCAT_OS;
	delete l->B_s0_TAGDECISION;
	delete l->B_s0_TAGDECISION_OS;
	delete l->B_s0_TAGGER;
	delete l->B_s0_TAGOMEGA;
	delete l->B_s0_TAGOMEGA_OS;
	delete l->B_s0_TAU;
	delete l->B_s0_TAUCHI2;
	delete l->B_s0_TAUERR;
	delete l->Kminus_ETA;
	delete l->Kminus_IPCHI2_OWNPV;
	delete l->Kminus_IP_OWNPV;
	delete l->Kminus_M;
	delete l->Kminus_ORIVX_CHI2;
	delete l->Kminus_P;
	delete l->Kminus_PE;
	delete l->Kminus_PIDK;
	delete l->Kminus_PIDe;
	delete l->Kminus_PIDmu;
	delete l->Kminus_PIDp;
	delete l->Kminus_PT;
	delete l->Kminus_PX;
	delete l->Kminus_PY;
	delete l->Kminus_PZ;
	delete l->Kminus_ProbNNk;
	delete l->Kminus_ProbNNkcorr;
	delete l->Kminus_ProbNNp;
	delete l->Kminus_ProbNNpi;
	delete l->Kminus_ProbNNpicorr;
	delete l->Kminus_TRACK_CHI2NDOF;
	delete l->Kminus_isMuon;
	delete l->Kplus_ETA;
	delete l->Kplus_IPCHI2_OWNPV;
	delete l->Kplus_IP_OWNPV;
	delete l->Kplus_M;
	delete l->Kplus_ORIVX_CHI2;
	delete l->Kplus_P;
	delete l->Kplus_PE;
	delete l->Kplus_PIDK;
	delete l->Kplus_PIDe;
	delete l->Kplus_PIDmu;
	delete l->Kplus_PIDp;
	delete l->Kplus_PT;
	delete l->Kplus_PX;
	delete l->Kplus_PY;
	delete l->Kplus_PZ;
	delete l->Kplus_ProbNNk;
	delete l->Kplus_ProbNNkcorr;
	delete l->Kplus_ProbNNp;
	delete l->Kplus_ProbNNpi;
	delete l->Kplus_ProbNNpicorr;
	delete l->Kplus_TRACK_CHI2NDOF;
	delete l->Kplus_isMuon;
	delete l->Kst_CosTheta;
	delete l->Kst_DIRA_ORIVX;
	delete l->Kst_DIRA_OWNPV;
	delete l->Kst_ENDVERTEX_CHI2;
	delete l->Kst_ETA;
	delete l->Kst_FDCHI2_ORIVX;
	delete l->Kst_FDCHI2_OWNPV;
	delete l->Kst_FD_ORIVX;
	delete l->Kst_FD_OWNPV;
	delete l->Kst_IPCHI2_OWNPV;
	delete l->Kst_IP_OWNPV;
	delete l->Kst_M;
	delete l->Kst_MM;
	delete l->Kst_MMERR;
	delete l->Kst_P;
	delete l->Kst_PE;
	delete l->Kst_PT;
	delete l->Kst_PX;
	delete l->Kst_PY;
	delete l->Kst_PZ;
	delete l->Kstb_CosTheta;
	delete l->Kstb_DIRA_ORIVX;
	delete l->Kstb_DIRA_OWNPV;
	delete l->Kstb_ENDVERTEX_CHI2;
	delete l->Kstb_ETA;
	delete l->Kstb_FDCHI2_ORIVX;
	delete l->Kstb_FDCHI2_OWNPV;
	delete l->Kstb_FD_ORIVX;
	delete l->Kstb_FD_OWNPV;
	delete l->Kstb_IPCHI2_OWNPV;
	delete l->Kstb_IP_OWNPV;
	delete l->Kstb_M;
	delete l->Kstb_MM;
	delete l->Kstb_MMERR;
	delete l->Kstb_P;
	delete l->Kstb_PE;
	delete l->Kstb_PT;
	delete l->Kstb_PX;
	delete l->Kstb_PY;
	delete l->Kstb_PZ;
	delete l->M_KKPiMinus;
	delete l->M_KKPiPlus;
	delete l->PVCHI2;
	delete l->PVNDOF;
	delete l->PVNTRACKS;
	delete l->PVX;
	delete l->PVXERR;
	delete l->PVY;
	delete l->PVYERR;
	delete l->PVZ;
	delete l->PVZERR;
	delete l->Piminus_ETA;
	delete l->Piminus_IPCHI2_OWNPV;
	delete l->Piminus_IP_OWNPV;
	delete l->Piminus_M;
	delete l->Piminus_ORIVX_CHI2;
	delete l->Piminus_P;
	delete l->Piminus_PE;
	delete l->Piminus_PIDK;
	delete l->Piminus_PIDe;
	delete l->Piminus_PIDmu;
	delete l->Piminus_PIDp;
	delete l->Piminus_PT;
	delete l->Piminus_PX;
	delete l->Piminus_PY;
	delete l->Piminus_PZ;
	delete l->Piminus_ProbNNk;
	delete l->Piminus_ProbNNkcorr;
	delete l->Piminus_ProbNNp;
	delete l->Piminus_ProbNNpi;
	delete l->Piminus_ProbNNpicorr;
	delete l->Piminus_TRACK_CHI2NDOF;
	delete l->Piminus_isMuon;
	delete l->Piplus_ETA;
	delete l->Piplus_IPCHI2_OWNPV;
	delete l->Piplus_IP_OWNPV;
	delete l->Piplus_M;
	delete l->Piplus_ORIVX_CHI2;
	delete l->Piplus_P;
	delete l->Piplus_PE;
	delete l->Piplus_PIDK;
	delete l->Piplus_PIDe;
	delete l->Piplus_PIDmu;
	delete l->Piplus_PIDp;
	delete l->Piplus_PT;
	delete l->Piplus_PX;
	delete l->Piplus_PY;
	delete l->Piplus_PZ;
	delete l->Piplus_ProbNNk;
	delete l->Piplus_ProbNNkcorr;
	delete l->Piplus_ProbNNp;
	delete l->Piplus_ProbNNpi;
	delete l->Piplus_ProbNNpicorr;
	delete l->Piplus_TRACK_CHI2NDOF;
	delete l->Piplus_isMuon;
	delete l->Polarity;
	delete l->cut_based_pid;
	delete l->eventNumber;
	delete l->max_track_chi2;
	delete l->nBackTracks;
	delete l->nCandidate;
	delete l->nDownstreamTracks;
	delete l->nITClusters;
	delete l->nLongTracks;
	delete l->nMuonCoordsS0;
	delete l->nMuonCoordsS1;
	delete l->nMuonCoordsS2;
	delete l->nMuonCoordsS3;
	delete l->nMuonCoordsS4;
	delete l->nMuonTracks;
	delete l->nOTClusters;
	delete l->nPV;
	delete l->nPVs;
	delete l->nRich1Hits;
	delete l->nRich2Hits;
	delete l->nSPDHits;
	delete l->nTTClusters;
	delete l->nTTracks;
	delete l->nTracks;
	delete l->nUpstreamTracks;
	delete l->nVeloClusters;
	delete l->nVeloTracks;
	delete l->runNumber;
	delete l->totCandidates;

	delete l->b_B_s0_BKGCAT;
	delete l->b_B_s0_DIRA_OWNPV;
	delete l->b_B_s0_ENDVERTEX_CHI2;
	delete l->b_B_s0_ETA;
	delete l->b_B_s0_FDCHI2_OWNPV;
	delete l->b_B_s0_FD_OWNPV;
	delete l->b_B_s0_Hlt1DiHadronDecision_TOS;
	delete l->b_B_s0_Hlt1SingleHadronDecision_TOS;
	delete l->b_B_s0_Hlt1TrackAllL0Decision_TOS;
	delete l->b_B_s0_Hlt2B2HHDecision_TOS;
	delete l->b_B_s0_Hlt2Topo2BodyBBDTDecision_TOS;
	delete l->b_B_s0_Hlt2Topo2BodySimpleDecision_TOS;
	delete l->b_B_s0_Hlt2Topo3BodyBBDTDecision_TOS;
	delete l->b_B_s0_Hlt2Topo3BodySimpleDecision_TOS;
	delete l->b_B_s0_Hlt2Topo4BodyBBDTDecision_TOS;
	delete l->b_B_s0_Hlt2Topo4BodySimpleDecision_TOS;
	delete l->b_B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS;
	delete l->b_B_s0_Hlt2TopoOSTF4BodyDecision_TOS;
	delete l->b_B_s0_IPCHI2_OWNPV;
	delete l->b_B_s0_IP_OWNPV;
	delete l->b_B_s0_L0Global_TIS;
	delete l->b_B_s0_L0HadronDecision_TOS;
	delete l->b_B_s0_M;
	delete l->b_B_s0_MC_GD_GD_MOTHER_ID;
	delete l->b_B_s0_MC_GD_GD_MOTHER_KEY;
	delete l->b_B_s0_MC_GD_MOTHER_ID;
	delete l->b_B_s0_MC_GD_MOTHER_KEY;
	delete l->b_B_s0_MC_MOTHER_ID;
	delete l->b_B_s0_MC_MOTHER_KEY;
	delete l->b_B_s0_MM;
	delete l->b_B_s0_MMERR;
	delete l->b_B_s0_OWNPV_CHI2;
	delete l->b_B_s0_P;
	delete l->b_B_s0_PE;
	delete l->b_B_s0_PT;
	delete l->b_B_s0_PX;
	delete l->b_B_s0_PY;
	delete l->b_B_s0_PZ;
	delete l->b_B_s0_Phi;
	delete l->b_B_s0_TAGCAT;
	delete l->b_B_s0_TAGCAT_OS;
	delete l->b_B_s0_TAGDECISION;
	delete l->b_B_s0_TAGDECISION_OS;
	delete l->b_B_s0_TAGGER;
	delete l->b_B_s0_TAGOMEGA;
	delete l->b_B_s0_TAGOMEGA_OS;
	delete l->b_B_s0_TAU;
	delete l->b_B_s0_TAUCHI2;
	delete l->b_B_s0_TAUERR;
	delete l->b_Kminus_ETA;
	delete l->b_Kminus_IPCHI2_OWNPV;
	delete l->b_Kminus_IP_OWNPV;
	delete l->b_Kminus_M;
	delete l->b_Kminus_ORIVX_CHI2;
	delete l->b_Kminus_P;
	delete l->b_Kminus_PE;
	delete l->b_Kminus_PIDK;
	delete l->b_Kminus_PIDe;
	delete l->b_Kminus_PIDmu;
	delete l->b_Kminus_PIDp;
	delete l->b_Kminus_PT;
	delete l->b_Kminus_PX;
	delete l->b_Kminus_PY;
	delete l->b_Kminus_PZ;
	delete l->b_Kminus_ProbNNk;
	delete l->b_Kminus_ProbNNkcorr;
	delete l->b_Kminus_ProbNNp;
	delete l->b_Kminus_ProbNNpi;
	delete l->b_Kminus_ProbNNpicorr;
	delete l->b_Kminus_TRACK_CHI2NDOF;
	delete l->b_Kminus_isMuon;
	delete l->b_Kplus_ETA;
	delete l->b_Kplus_IPCHI2_OWNPV;
	delete l->b_Kplus_IP_OWNPV;
	delete l->b_Kplus_M;
	delete l->b_Kplus_ORIVX_CHI2;
	delete l->b_Kplus_P;
	delete l->b_Kplus_PE;
	delete l->b_Kplus_PIDK;
	delete l->b_Kplus_PIDe;
	delete l->b_Kplus_PIDmu;
	delete l->b_Kplus_PIDp;
	delete l->b_Kplus_PT;
	delete l->b_Kplus_PX;
	delete l->b_Kplus_PY;
	delete l->b_Kplus_PZ;
	delete l->b_Kplus_ProbNNk;
	delete l->b_Kplus_ProbNNkcorr;
	delete l->b_Kplus_ProbNNp;
	delete l->b_Kplus_ProbNNpi;
	delete l->b_Kplus_ProbNNpicorr;
	delete l->b_Kplus_TRACK_CHI2NDOF;
	delete l->b_Kplus_isMuon;
	delete l->b_Kst_CosTheta;
	delete l->b_Kst_DIRA_ORIVX;
	delete l->b_Kst_DIRA_OWNPV;
	delete l->b_Kst_ENDVERTEX_CHI2;
	delete l->b_Kst_ETA;
	delete l->b_Kst_FDCHI2_ORIVX;
	delete l->b_Kst_FDCHI2_OWNPV;
	delete l->b_Kst_FD_ORIVX;
	delete l->b_Kst_FD_OWNPV;
	delete l->b_Kst_IPCHI2_OWNPV;
	delete l->b_Kst_IP_OWNPV;
	delete l->b_Kst_M;
	delete l->b_Kst_MM;
	delete l->b_Kst_MMERR;
	delete l->b_Kst_P;
	delete l->b_Kst_PE;
	delete l->b_Kst_PT;
	delete l->b_Kst_PX;
	delete l->b_Kst_PY;
	delete l->b_Kst_PZ;
	delete l->b_Kstb_CosTheta;
	delete l->b_Kstb_DIRA_ORIVX;
	delete l->b_Kstb_DIRA_OWNPV;
	delete l->b_Kstb_ENDVERTEX_CHI2;
	delete l->b_Kstb_ETA;
	delete l->b_Kstb_FDCHI2_ORIVX;
	delete l->b_Kstb_FDCHI2_OWNPV;
	delete l->b_Kstb_FD_ORIVX;
	delete l->b_Kstb_FD_OWNPV;
	delete l->b_Kstb_IPCHI2_OWNPV;
	delete l->b_Kstb_IP_OWNPV;
	delete l->b_Kstb_M;
	delete l->b_Kstb_MM;
	delete l->b_Kstb_MMERR;
	delete l->b_Kstb_P;
	delete l->b_Kstb_PE;
	delete l->b_Kstb_PT;
	delete l->b_Kstb_PX;
	delete l->b_Kstb_PY;
	delete l->b_Kstb_PZ;
	delete l->b_M_KKPiMinus;
	delete l->b_M_KKPiPlus;
	delete l->b_PVCHI2;
	delete l->b_PVNDOF;
	delete l->b_PVNTRACKS;
	delete l->b_PVX;
	delete l->b_PVXERR;
	delete l->b_PVY;
	delete l->b_PVYERR;
	delete l->b_PVZ;
	delete l->b_PVZERR;
	delete l->b_Piminus_ETA;
	delete l->b_Piminus_IPCHI2_OWNPV;
	delete l->b_Piminus_IP_OWNPV;
	delete l->b_Piminus_M;
	delete l->b_Piminus_ORIVX_CHI2;
	delete l->b_Piminus_P;
	delete l->b_Piminus_PE;
	delete l->b_Piminus_PIDK;
	delete l->b_Piminus_PIDe;
	delete l->b_Piminus_PIDmu;
	delete l->b_Piminus_PIDp;
	delete l->b_Piminus_PT;
	delete l->b_Piminus_PX;
	delete l->b_Piminus_PY;
	delete l->b_Piminus_PZ;
	delete l->b_Piminus_ProbNNk;
	delete l->b_Piminus_ProbNNkcorr;
	delete l->b_Piminus_ProbNNp;
	delete l->b_Piminus_ProbNNpi;
	delete l->b_Piminus_ProbNNpicorr;
	delete l->b_Piminus_TRACK_CHI2NDOF;
	delete l->b_Piminus_isMuon;
	delete l->b_Piplus_ETA;
	delete l->b_Piplus_IPCHI2_OWNPV;
	delete l->b_Piplus_IP_OWNPV;
	delete l->b_Piplus_M;
	delete l->b_Piplus_ORIVX_CHI2;
	delete l->b_Piplus_P;
	delete l->b_Piplus_PE;
	delete l->b_Piplus_PIDK;
	delete l->b_Piplus_PIDe;
	delete l->b_Piplus_PIDmu;
	delete l->b_Piplus_PIDp;
	delete l->b_Piplus_PT;
	delete l->b_Piplus_PX;
	delete l->b_Piplus_PY;
	delete l->b_Piplus_PZ;
	delete l->b_Piplus_ProbNNk;
	delete l->b_Piplus_ProbNNkcorr;
	delete l->b_Piplus_ProbNNp;
	delete l->b_Piplus_ProbNNpi;
	delete l->b_Piplus_ProbNNpicorr;
	delete l->b_Piplus_TRACK_CHI2NDOF;
	delete l->b_Piplus_isMuon;
	delete l->b_Polarity;
	delete l->b_cut_based_pid;
	delete l->b_eventNumber;
	delete l->b_max_track_chi2;
	delete l->b_nBackTracks;
	delete l->b_nCandidate;
	delete l->b_nDownstreamTracks;
	delete l->b_nITClusters;
	delete l->b_nLongTracks;
	delete l->b_nMuonCoordsS0;
	delete l->b_nMuonCoordsS1;
	delete l->b_nMuonCoordsS2;
	delete l->b_nMuonCoordsS3;
	delete l->b_nMuonCoordsS4;
	delete l->b_nMuonTracks;
	delete l->b_nOTClusters;
	delete l->b_nPV;
	delete l->b_nPVs;
	delete l->b_nRich1Hits;
	delete l->b_nRich2Hits;
	delete l->b_nSPDHits;
	delete l->b_nTTClusters;
	delete l->b_nTTracks;
	delete l->b_nTracks;
	delete l->b_nUpstreamTracks;
	delete l->b_nVeloClusters;
	delete l->b_nVeloTracks;
	delete l->b_runNumber;
	delete l->b_totCandidates;
}

void PIDCalibBranches::setOutputBranches(Looper *l, TTree *tree){ 
	tree->Branch("itype",&(l->itype));
	tree->Branch("sqrts",&(l->sqrts));
	tree->Branch("B_s0_BKGCAT",l->B_s0_BKGCAT);
	tree->Branch("B_s0_DIRA_OWNPV",l->B_s0_DIRA_OWNPV);
	tree->Branch("B_s0_ENDVERTEX_CHI2",l->B_s0_ENDVERTEX_CHI2);
	tree->Branch("B_s0_ETA",l->B_s0_ETA);
	tree->Branch("B_s0_FDCHI2_OWNPV",l->B_s0_FDCHI2_OWNPV);
	tree->Branch("B_s0_FD_OWNPV",l->B_s0_FD_OWNPV);
	tree->Branch("B_s0_Hlt1DiHadronDecision_TOS",l->B_s0_Hlt1DiHadronDecision_TOS);
	tree->Branch("B_s0_Hlt1SingleHadronDecision_TOS",l->B_s0_Hlt1SingleHadronDecision_TOS);
	tree->Branch("B_s0_Hlt1TrackAllL0Decision_TOS",l->B_s0_Hlt1TrackAllL0Decision_TOS);
	tree->Branch("B_s0_Hlt2B2HHDecision_TOS",l->B_s0_Hlt2B2HHDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo2BodyBBDTDecision_TOS",l->B_s0_Hlt2Topo2BodyBBDTDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo2BodySimpleDecision_TOS",l->B_s0_Hlt2Topo2BodySimpleDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo3BodyBBDTDecision_TOS",l->B_s0_Hlt2Topo3BodyBBDTDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo3BodySimpleDecision_TOS",l->B_s0_Hlt2Topo3BodySimpleDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo4BodyBBDTDecision_TOS",l->B_s0_Hlt2Topo4BodyBBDTDecision_TOS);
	tree->Branch("B_s0_Hlt2Topo4BodySimpleDecision_TOS",l->B_s0_Hlt2Topo4BodySimpleDecision_TOS);
	tree->Branch("B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS",l->B_s0_Hlt2TopoMu4BodyBBDTDecision_TOS);
	tree->Branch("B_s0_Hlt2TopoOSTF4BodyDecision_TOS",l->B_s0_Hlt2TopoOSTF4BodyDecision_TOS);
	tree->Branch("B_s0_IPCHI2_OWNPV",l->B_s0_IPCHI2_OWNPV);
	tree->Branch("B_s0_IP_OWNPV",l->B_s0_IP_OWNPV);
	tree->Branch("B_s0_L0Global_TIS",l->B_s0_L0Global_TIS);
	tree->Branch("B_s0_L0HadronDecision_TOS",l->B_s0_L0HadronDecision_TOS);
	tree->Branch("B_s0_M",l->B_s0_M);
	tree->Branch("B_s0_MC_GD_GD_MOTHER_ID",l->B_s0_MC_GD_GD_MOTHER_ID);
	tree->Branch("B_s0_MC_GD_GD_MOTHER_KEY",l->B_s0_MC_GD_GD_MOTHER_KEY);
	tree->Branch("B_s0_MC_GD_MOTHER_ID",l->B_s0_MC_GD_MOTHER_ID);
	tree->Branch("B_s0_MC_GD_MOTHER_KEY",l->B_s0_MC_GD_MOTHER_KEY);
	tree->Branch("B_s0_MC_MOTHER_ID",l->B_s0_MC_MOTHER_ID);
	tree->Branch("B_s0_MC_MOTHER_KEY",l->B_s0_MC_MOTHER_KEY);
	tree->Branch("B_s0_MM",l->B_s0_MM);
	tree->Branch("B_s0_MMERR",l->B_s0_MMERR);
	tree->Branch("B_s0_OWNPV_CHI2",l->B_s0_OWNPV_CHI2);
	tree->Branch("B_s0_P",l->B_s0_P);
	tree->Branch("B_s0_PE",l->B_s0_PE);
	tree->Branch("B_s0_PT",l->B_s0_PT);
	tree->Branch("B_s0_PX",l->B_s0_PX);
	tree->Branch("B_s0_PY",l->B_s0_PY);
	tree->Branch("B_s0_PZ",l->B_s0_PZ);
	tree->Branch("B_s0_Phi",l->B_s0_Phi);
	tree->Branch("B_s0_TAGCAT",l->B_s0_TAGCAT);
	tree->Branch("B_s0_TAGCAT_OS",l->B_s0_TAGCAT_OS);
	tree->Branch("B_s0_TAGDECISION",l->B_s0_TAGDECISION);
	tree->Branch("B_s0_TAGDECISION_OS",l->B_s0_TAGDECISION_OS);
	tree->Branch("B_s0_TAGGER",l->B_s0_TAGGER);
	tree->Branch("B_s0_TAGOMEGA",l->B_s0_TAGOMEGA);
	tree->Branch("B_s0_TAGOMEGA_OS",l->B_s0_TAGOMEGA_OS);
	tree->Branch("B_s0_TAU",l->B_s0_TAU);
	tree->Branch("B_s0_TAUCHI2",l->B_s0_TAUCHI2);
	tree->Branch("B_s0_TAUERR",l->B_s0_TAUERR);
	tree->Branch("Kminus_ETA",l->Kminus_ETA);
	tree->Branch("Kminus_IPCHI2_OWNPV",l->Kminus_IPCHI2_OWNPV);
	tree->Branch("Kminus_IP_OWNPV",l->Kminus_IP_OWNPV);
	tree->Branch("Kminus_M",l->Kminus_M);
	tree->Branch("Kminus_ORIVX_CHI2",l->Kminus_ORIVX_CHI2);
	tree->Branch("Kminus_P",l->Kminus_P);
	tree->Branch("Kminus_PE",l->Kminus_PE);
	tree->Branch("Kminus_PIDK",l->Kminus_PIDK);
	tree->Branch("Kminus_PIDe",l->Kminus_PIDe);
	tree->Branch("Kminus_PIDmu",l->Kminus_PIDmu);
	tree->Branch("Kminus_PIDp",l->Kminus_PIDp);
	tree->Branch("Kminus_PT",l->Kminus_PT);
	tree->Branch("Kminus_PX",l->Kminus_PX);
	tree->Branch("Kminus_PY",l->Kminus_PY);
	tree->Branch("Kminus_PZ",l->Kminus_PZ);
	tree->Branch("Kminus_ProbNNk",l->Kminus_ProbNNk);
	tree->Branch("Kminus_ProbNNkcorr",l->Kminus_ProbNNkcorr);
	tree->Branch("Kminus_ProbNNp",l->Kminus_ProbNNp);
	tree->Branch("Kminus_ProbNNpi",l->Kminus_ProbNNpi);
	tree->Branch("Kminus_ProbNNpicorr",l->Kminus_ProbNNpicorr);
	tree->Branch("Kminus_TRACK_CHI2NDOF",l->Kminus_TRACK_CHI2NDOF);
	tree->Branch("Kminus_isMuon",l->Kminus_isMuon);
	tree->Branch("Kplus_ETA",l->Kplus_ETA);
	tree->Branch("Kplus_IPCHI2_OWNPV",l->Kplus_IPCHI2_OWNPV);
	tree->Branch("Kplus_IP_OWNPV",l->Kplus_IP_OWNPV);
	tree->Branch("Kplus_M",l->Kplus_M);
	tree->Branch("Kplus_ORIVX_CHI2",l->Kplus_ORIVX_CHI2);
	tree->Branch("Kplus_P",l->Kplus_P);
	tree->Branch("Kplus_PE",l->Kplus_PE);
	tree->Branch("Kplus_PIDK",l->Kplus_PIDK);
	tree->Branch("Kplus_PIDe",l->Kplus_PIDe);
	tree->Branch("Kplus_PIDmu",l->Kplus_PIDmu);
	tree->Branch("Kplus_PIDp",l->Kplus_PIDp);
	tree->Branch("Kplus_PT",l->Kplus_PT);
	tree->Branch("Kplus_PX",l->Kplus_PX);
	tree->Branch("Kplus_PY",l->Kplus_PY);
	tree->Branch("Kplus_PZ",l->Kplus_PZ);
	tree->Branch("Kplus_ProbNNk",l->Kplus_ProbNNk);
	tree->Branch("Kplus_ProbNNkcorr",l->Kplus_ProbNNkcorr);
	tree->Branch("Kplus_ProbNNp",l->Kplus_ProbNNp);
	tree->Branch("Kplus_ProbNNpi",l->Kplus_ProbNNpi);
	tree->Branch("Kplus_ProbNNpicorr",l->Kplus_ProbNNpicorr);
	tree->Branch("Kplus_TRACK_CHI2NDOF",l->Kplus_TRACK_CHI2NDOF);
	tree->Branch("Kplus_isMuon",l->Kplus_isMuon);
	tree->Branch("Kst_CosTheta",l->Kst_CosTheta);
	tree->Branch("Kst_DIRA_ORIVX",l->Kst_DIRA_ORIVX);
	tree->Branch("Kst_DIRA_OWNPV",l->Kst_DIRA_OWNPV);
	tree->Branch("Kst_ENDVERTEX_CHI2",l->Kst_ENDVERTEX_CHI2);
	tree->Branch("Kst_ETA",l->Kst_ETA);
	tree->Branch("Kst_FDCHI2_ORIVX",l->Kst_FDCHI2_ORIVX);
	tree->Branch("Kst_FDCHI2_OWNPV",l->Kst_FDCHI2_OWNPV);
	tree->Branch("Kst_FD_ORIVX",l->Kst_FD_ORIVX);
	tree->Branch("Kst_FD_OWNPV",l->Kst_FD_OWNPV);
	tree->Branch("Kst_IPCHI2_OWNPV",l->Kst_IPCHI2_OWNPV);
	tree->Branch("Kst_IP_OWNPV",l->Kst_IP_OWNPV);
	tree->Branch("Kst_M",l->Kst_M);
	tree->Branch("Kst_MM",l->Kst_MM);
	tree->Branch("Kst_MMERR",l->Kst_MMERR);
	tree->Branch("Kst_P",l->Kst_P);
	tree->Branch("Kst_PE",l->Kst_PE);
	tree->Branch("Kst_PT",l->Kst_PT);
	tree->Branch("Kst_PX",l->Kst_PX);
	tree->Branch("Kst_PY",l->Kst_PY);
	tree->Branch("Kst_PZ",l->Kst_PZ);
	tree->Branch("Kstb_CosTheta",l->Kstb_CosTheta);
	tree->Branch("Kstb_DIRA_ORIVX",l->Kstb_DIRA_ORIVX);
	tree->Branch("Kstb_DIRA_OWNPV",l->Kstb_DIRA_OWNPV);
	tree->Branch("Kstb_ENDVERTEX_CHI2",l->Kstb_ENDVERTEX_CHI2);
	tree->Branch("Kstb_ETA",l->Kstb_ETA);
	tree->Branch("Kstb_FDCHI2_ORIVX",l->Kstb_FDCHI2_ORIVX);
	tree->Branch("Kstb_FDCHI2_OWNPV",l->Kstb_FDCHI2_OWNPV);
	tree->Branch("Kstb_FD_ORIVX",l->Kstb_FD_ORIVX);
	tree->Branch("Kstb_FD_OWNPV",l->Kstb_FD_OWNPV);
	tree->Branch("Kstb_IPCHI2_OWNPV",l->Kstb_IPCHI2_OWNPV);
	tree->Branch("Kstb_IP_OWNPV",l->Kstb_IP_OWNPV);
	tree->Branch("Kstb_M",l->Kstb_M);
	tree->Branch("Kstb_MM",l->Kstb_MM);
	tree->Branch("Kstb_MMERR",l->Kstb_MMERR);
	tree->Branch("Kstb_P",l->Kstb_P);
	tree->Branch("Kstb_PE",l->Kstb_PE);
	tree->Branch("Kstb_PT",l->Kstb_PT);
	tree->Branch("Kstb_PX",l->Kstb_PX);
	tree->Branch("Kstb_PY",l->Kstb_PY);
	tree->Branch("Kstb_PZ",l->Kstb_PZ);
	tree->Branch("M_KKPiMinus",l->M_KKPiMinus);
	tree->Branch("M_KKPiPlus",l->M_KKPiPlus);
	tree->Branch("PVCHI2",l->PVCHI2);
	tree->Branch("PVNDOF",l->PVNDOF);
	tree->Branch("PVNTRACKS",l->PVNTRACKS);
	tree->Branch("PVX",l->PVX);
	tree->Branch("PVXERR",l->PVXERR);
	tree->Branch("PVY",l->PVY);
	tree->Branch("PVYERR",l->PVYERR);
	tree->Branch("PVZ",l->PVZ);
	tree->Branch("PVZERR",l->PVZERR);
	tree->Branch("Piminus_ETA",l->Piminus_ETA);
	tree->Branch("Piminus_IPCHI2_OWNPV",l->Piminus_IPCHI2_OWNPV);
	tree->Branch("Piminus_IP_OWNPV",l->Piminus_IP_OWNPV);
	tree->Branch("Piminus_M",l->Piminus_M);
	tree->Branch("Piminus_ORIVX_CHI2",l->Piminus_ORIVX_CHI2);
	tree->Branch("Piminus_P",l->Piminus_P);
	tree->Branch("Piminus_PE",l->Piminus_PE);
	tree->Branch("Piminus_PIDK",l->Piminus_PIDK);
	tree->Branch("Piminus_PIDe",l->Piminus_PIDe);
	tree->Branch("Piminus_PIDmu",l->Piminus_PIDmu);
	tree->Branch("Piminus_PIDp",l->Piminus_PIDp);
	tree->Branch("Piminus_PT",l->Piminus_PT);
	tree->Branch("Piminus_PX",l->Piminus_PX);
	tree->Branch("Piminus_PY",l->Piminus_PY);
	tree->Branch("Piminus_PZ",l->Piminus_PZ);
	tree->Branch("Piminus_ProbNNk",l->Piminus_ProbNNk);
	tree->Branch("Piminus_ProbNNkcorr",l->Piminus_ProbNNkcorr);
	tree->Branch("Piminus_ProbNNp",l->Piminus_ProbNNp);
	tree->Branch("Piminus_ProbNNpi",l->Piminus_ProbNNpi);
	tree->Branch("Piminus_ProbNNpicorr",l->Piminus_ProbNNpicorr);
	tree->Branch("Piminus_TRACK_CHI2NDOF",l->Piminus_TRACK_CHI2NDOF);
	tree->Branch("Piminus_isMuon",l->Piminus_isMuon);
	tree->Branch("Piplus_ETA",l->Piplus_ETA);
	tree->Branch("Piplus_IPCHI2_OWNPV",l->Piplus_IPCHI2_OWNPV);
	tree->Branch("Piplus_IP_OWNPV",l->Piplus_IP_OWNPV);
	tree->Branch("Piplus_M",l->Piplus_M);
	tree->Branch("Piplus_ORIVX_CHI2",l->Piplus_ORIVX_CHI2);
	tree->Branch("Piplus_P",l->Piplus_P);
	tree->Branch("Piplus_PE",l->Piplus_PE);
	tree->Branch("Piplus_PIDK",l->Piplus_PIDK);
	tree->Branch("Piplus_PIDe",l->Piplus_PIDe);
	tree->Branch("Piplus_PIDmu",l->Piplus_PIDmu);
	tree->Branch("Piplus_PIDp",l->Piplus_PIDp);
	tree->Branch("Piplus_PT",l->Piplus_PT);
	tree->Branch("Piplus_PX",l->Piplus_PX);
	tree->Branch("Piplus_PY",l->Piplus_PY);
	tree->Branch("Piplus_PZ",l->Piplus_PZ);
	tree->Branch("Piplus_ProbNNk",l->Piplus_ProbNNk);
	tree->Branch("Piplus_ProbNNkcorr",l->Piplus_ProbNNkcorr);
	tree->Branch("Piplus_ProbNNp",l->Piplus_ProbNNp);
	tree->Branch("Piplus_ProbNNpi",l->Piplus_ProbNNpi);
	tree->Branch("Piplus_ProbNNpicorr",l->Piplus_ProbNNpicorr);
	tree->Branch("Piplus_TRACK_CHI2NDOF",l->Piplus_TRACK_CHI2NDOF);
	tree->Branch("Piplus_isMuon",l->Piplus_isMuon);
	tree->Branch("Polarity",l->Polarity);
	tree->Branch("cut_based_pid",l->cut_based_pid);
	tree->Branch("eventNumber",l->eventNumber);
	tree->Branch("max_track_chi2",l->max_track_chi2);
	tree->Branch("nBackTracks",l->nBackTracks);
	tree->Branch("nCandidate",l->nCandidate);
	tree->Branch("nDownstreamTracks",l->nDownstreamTracks);
	tree->Branch("nITClusters",l->nITClusters);
	tree->Branch("nLongTracks",l->nLongTracks);
	tree->Branch("nMuonCoordsS0",l->nMuonCoordsS0);
	tree->Branch("nMuonCoordsS1",l->nMuonCoordsS1);
	tree->Branch("nMuonCoordsS2",l->nMuonCoordsS2);
	tree->Branch("nMuonCoordsS3",l->nMuonCoordsS3);
	tree->Branch("nMuonCoordsS4",l->nMuonCoordsS4);
	tree->Branch("nMuonTracks",l->nMuonTracks);
	tree->Branch("nOTClusters",l->nOTClusters);
	tree->Branch("nPV",l->nPV);
	tree->Branch("nPVs",l->nPVs);
	tree->Branch("nRich1Hits",l->nRich1Hits);
	tree->Branch("nRich2Hits",l->nRich2Hits);
	tree->Branch("nSPDHits",l->nSPDHits);
	tree->Branch("nTTClusters",l->nTTClusters);
	tree->Branch("nTTracks",l->nTTracks);
	tree->Branch("nTracks",l->nTracks);
	tree->Branch("nUpstreamTracks",l->nUpstreamTracks);
	tree->Branch("nVeloClusters",l->nVeloClusters);
	tree->Branch("nVeloTracks",l->nVeloTracks);
	tree->Branch("runNumber",l->runNumber);
	tree->Branch("totCandidates",l->totCandidates);
}

